# Generated by Django 2.2.3 on 2019-11-12 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(blank=True, max_length=1000)),
                ('action', models.CharField(blank=True, max_length=1000)),
                ('goal', models.CharField(blank=True, max_length=1000)),
                ('conclusion', models.CharField(blank=True, max_length=1000)),
                ('agree', models.ManyToManyField(blank=True, related_name='agree', to=settings.AUTH_USER_MODEL)),
                ('disagree', models.ManyToManyField(blank=True, related_name='disagree', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
