# Generated by Django 2.2.3 on 2019-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='argtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='debate',
            name='argtypenum',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='debate',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
