from django.db import models
from django.contrib.auth.models import User

class debate(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True)
    title = models.CharField(max_length=100,blank=True)
    argtype = models.CharField(max_length=50,blank=True)
    argtypenum = models.IntegerField(default=7)
    a1 = models.CharField(max_length=200,blank=True)
    a2 = models.CharField(max_length=200,blank=True)
    a3 = models.CharField(max_length=200,blank=True)
    a4 = models.CharField(max_length=200,blank=True)
    a5 = models.CharField(max_length=200,blank=True)
    a6 = models.CharField(max_length=200,blank=True)
    a7 = models.CharField(max_length=200,blank=True)
    al1 = models.IntegerField(default=0)
    al2 = models.IntegerField(default=0)
    al3 = models.IntegerField(default=0)
    al4 = models.IntegerField(default=0)
    al5 = models.IntegerField(default=0)
    al6 = models.IntegerField(default=0)
    al7 = models.IntegerField(default=0)
    ad1 = models.IntegerField(default=0)
    ad2 = models.IntegerField(default=0)
    ad3 = models.IntegerField(default=0)
    ad4 = models.IntegerField(default=0)
    ad5 = models.IntegerField(default=0)
    ad6 = models.IntegerField(default=0)
    ad7 = models.IntegerField(default=0)
    anum = models.IntegerField(default=1)
    b1 = models.CharField(max_length=200,blank=True)
    b2 = models.CharField(max_length=200,blank=True)
    b3 = models.CharField(max_length=200,blank=True)
    b4 = models.CharField(max_length=200,blank=True)
    b5 = models.CharField(max_length=200,blank=True)
    b6 = models.CharField(max_length=200,blank=True)
    b7 = models.CharField(max_length=200,blank=True)
    bl1 = models.IntegerField(default=0)
    bl2 = models.IntegerField(default=0)
    bl3 = models.IntegerField(default=0)
    bl4 = models.IntegerField(default=0)
    bl5 = models.IntegerField(default=0)
    bl6 = models.IntegerField(default=0)
    bl7 = models.IntegerField(default=0)
    bd1 = models.IntegerField(default=0)
    bd2 = models.IntegerField(default=0)
    bd3 = models.IntegerField(default=0)
    bd4 = models.IntegerField(default=0)
    bd5 = models.IntegerField(default=0)
    bd6 = models.IntegerField(default=0)
    bd7 = models.IntegerField(default=0)
    bnum = models.IntegerField(default=1)
    c1 = models.CharField(max_length=200,blank=True)
    c2 = models.CharField(max_length=200,blank=True)
    c3 = models.CharField(max_length=200,blank=True)
    c4 = models.CharField(max_length=200,blank=True)
    c5 = models.CharField(max_length=200,blank=True)
    c6 = models.CharField(max_length=200,blank=True)
    c7 = models.CharField(max_length=200,blank=True)
    cl1 = models.IntegerField(default=0)
    cl2 = models.IntegerField(default=0)
    cl3 = models.IntegerField(default=0)
    cl4 = models.IntegerField(default=0)
    cl5 = models.IntegerField(default=0)
    cl6 = models.IntegerField(default=0)
    cl7 = models.IntegerField(default=0)
    cd1 = models.IntegerField(default=0)
    cd2 = models.IntegerField(default=0)
    cd3 = models.IntegerField(default=0)
    cd4 = models.IntegerField(default=0)
    cd5 = models.IntegerField(default=0)
    cd6 = models.IntegerField(default=0)
    cd7 = models.IntegerField(default=0)
    cnum = models.IntegerField(default=1)
    d1 = models.CharField(max_length=200,blank=True)
    d2 = models.CharField(max_length=200,blank=True)
    d3 = models.CharField(max_length=200,blank=True)
    d4 = models.CharField(max_length=200,blank=True)
    d5 = models.CharField(max_length=200,blank=True)
    d6 = models.CharField(max_length=200,blank=True)
    d7 = models.CharField(max_length=200,blank=True)
    dl1 = models.IntegerField(default=0)
    dl2 = models.IntegerField(default=0)
    dl3 = models.IntegerField(default=0)
    dl4 = models.IntegerField(default=0)
    dl5 = models.IntegerField(default=0)
    dl6 = models.IntegerField(default=0)
    dl7 = models.IntegerField(default=0)
    dd1 = models.IntegerField(default=0)
    dd2 = models.IntegerField(default=0)
    dd3 = models.IntegerField(default=0)
    dd4 = models.IntegerField(default=0)
    dd5 = models.IntegerField(default=0)
    dd6 = models.IntegerField(default=0)
    dd7 = models.IntegerField(default=0)
    dnum = models.IntegerField(default=1)
    link = models.ManyToManyField('posting.debate',blank=True)
    linkcheck = models.BooleanField(default=False)

    def __str__(self):
        return (self.title)

    def getagrees(self):
        return (self.al1+self.al2+self.al3+self.al4+self.al5+self.al6+self.al7+self.bl1+self.bl2+self.bl3+self.bl4+self.bl5+self.bl6+self.bl7+self.cl1+self.cl2+self.cl3+self.cl4+self.cl5+self.cl6+self.cl7+self.dl1+self.dl2+self.dl3+self.dl4+self.dl5+self.dl6+self.dl7)

    def getdisagrees(self):
        return (self.ad1+self.ad2+self.ad3+self.ad4+self.ad5+self.ad6+self.ad7+self.bd1+self.bd2+self.bd3+self.bd4+self.bd5+self.bd6+self.bd7+self.cd1+self.cd2+self.cd3+self.cd4+self.cd5+self.cd6+self.cd7+self.dd1+self.dd2+self.dd3+self.dd4+self.dd5+self.dd6+self.dd7)